import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: {
      default: "Create Next App",
      template: "%s | Next JS APP"
   },
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <div className="container">
               <Navbar />
               <main>
                  {children}
               </main>
               <Footer />
            </div>
         </body>
      </html>
   );
}
