import { Suspense } from 'react';
import styles from './admin.module.scss'
import AdminPosts from '@/components/elements/adminPosts/adminPosts';
import AdminPostForm from '@/components/elements/adminPostForm/adminPostForm';
import AdminUsers from '@/components/elements/adminUsers/adminUsers';
import AdminUserForm from '@/components/elements/adminUserForm/adminUserForm';

export const metadata = {
   title: "Admin",
   description: "Generated by create next app",
};

export default function AdminPage() {
   return (
      <div className={styles.admin}>
         <div className={styles.row}>
            <div className={styles.col}>
               <Suspense fallback={<div>Loading...</div>}>
                  <AdminPosts />
               </Suspense>
            </div>
            <div className={styles.col}>
               <AdminPostForm />
            </div>
         </div>
         <div className={styles.row}>
            <div className={styles.col}>
               <Suspense fallback={<div>Loading...</div>}>
                  <AdminUsers />
               </Suspense>
            </div>
            <div className={styles.col}>
               <AdminUserForm />
            </div>
         </div>
      </div>
   )
}
