import Posts from '@/components/elements/posts/Posts'
import styles from './blog.module.scss'
import { getPosts } from '@/lib/data'

export const metadata = {
   title: "Blog Page",
   description: "Generated by create next app",
};

const getData = async () => {
   const res = await fetch("http://localhost:3000/api/blog", {
      next: {
         revalidate: 3600,
      }
   })
   const data = await res.json()
   if (!res.ok) {
      throw new Error("Error")
   }
   return data
}

export default async function BlogPage() {
   const posts = await getData()
   // const posts = await getPosts()

   return (
      <section className={styles.blogPage}>
         {posts.map((post) => (
            <div key={post.id} className={styles.postsPage}>
               <Posts post={post} />
            </div>
         ))}
      </section>
   )
}
